Add obsolete rule converter
typescript-eslint/tslint-to-eslint-config pull request #1063
Opened 2021-05-17 18:08 UTC by KingDarBoja

Used for prefer-inline-decorators and import-destructuring-spacing converters

## PR Checklist

-   [x] Addresses an existing issue: fixes #490, #472
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

Also includes a obsolete rule function and test stub for making it easier to use.

2021-05-18 14:51 UTC, JoshuaKGoldberg requested changes
Love it. Just the one request, I think it's a little odd to use `""` when what we really want is for the rule name to not exist.

2021-05-19 01:14 UTC, KingDarBoja commented on src/converters/lintConfigs/rules/obsoleteRule.stubs.ts
> +                        ruleName: "",
I was awaiting for your suggestion, I guess there is no harm making it optional? :D Haven't tried it and got lazy at the time being.

2021-07-03 15:24 UTC, JoshuaKGoldberg commented on src/converters/lintConfigs/rules/obsoleteRule.stubs.ts
> +                        ruleName: "",
@KingDarBoja do you plan on adding that in? I can if you don't have the time!

2021-07-03 21:45 UTC, JoshuaKGoldberg commented on src/converters/lintConfigs/rules/obsoleteRule.stubs.ts
> +                        ruleName: "",
Hmm, I'm playing around with this and it looks like it's a non-trivial. In `convertRules.ts` the output `rules` from the converters are stored in a `converted` map that stores by output ESLint name. 

I'll try spinning up a changeset that shows not outputting _any_ output ESLint `rules` for obsolete TSLint inputs.

2021-07-06 14:21 UTC, KingDarBoja commented on src/converters/lintConfigs/rules/obsoleteRule.stubs.ts
> +                        ruleName: "",
Thanks!

2021-07-14 17:16 UTC, JoshuaKGoldberg commented
#1148 was merged; closing this in favor of it. Thanks!

2021-07-14 17:16 UTC, closed without merging