docs: Fix broken link to `Dependencies.md`
typescript-eslint/tslint-to-eslint-config pull request #1370
Opened 2022-02-22 06:52 UTC by hyperupcall

## PR Checklist

-   [x] Fixes #937
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

The [typedef](https://palantir.github.io/tslint/rules/typedef/) property of TSLint is now considered during the conversion. All config options except `call-signature` and `arrow-call-signature` are accounted for. Options unaccounted for are mentioned in the `notices` array, when applicable

The linked issue and the [ESLint typedef docs](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/typedef.md) mentions that [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) and [explicit-module-boundary-types](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md) should be used when converting `call-signature` and `arrow-call-signature`. I did that in a separate branch [here](https://github.com/hyperupcall/tslint-to-eslint-config/commit/b99f54eaa8a4bc1e1fe0729b6b80d5069f77572d), but I wasn't 100% confident that my conversion was correct, so I left it out for now. If it is close to what is considered acceptable, maybe I can add it to this PR?

2022-02-22 14:50 UTC, JoshuaKGoldberg requested changes
Awesome, looks good so far. Glad to see this rule finally getting taken care of! 👏

Tests are failing ([ci link](https://app.circleci.com/pipelines/github/typescript-eslint/tslint-to-eslint-config/2825/workflows/a2ef8400-b46d-49c9-a9f0-db9f1da268e6/jobs/14581)) because a lack of coverage on lines `11,15,19,27,31`. You'll want to add >=1 test case that covers them.

2022-02-22 15:04 UTC, JoshuaKGoldberg commented
> install @swc/core to get things to run

Huh, sorry about that - I'll send a separate PR to add it in.

2022-02-22 15:14 UTC, JoshuaKGoldberg commented
>  Node 12 works, but 14 was the minimum LTS that worked for me (Jest threw SyntaxError: Unexpected token '.' when it encountered optional chaining)

Nice, following up on that too: https://github.com/typescript-eslint/tslint-to-eslint-config/pull/1374

2022-02-24 07:11 UTC, hyperupcall commented on src/converters/lintConfigs/rules/ruleConverters/typedef.ts
> +        ...(tslintRule.ruleArguments.some(
Good idea :+1: I'll make those changes

2022-02-24 07:13 UTC, hyperupcall commented on src/converters/lintConfigs/rules/ruleConverters/typedef.ts
> +            notices: ["Options 'call-signature' and 'arrow-call-signature' are ignored"],
Cool, I'll add that in too

2022-02-24 07:18 UTC, hyperupcall commented
Thank you for your feedback! :smiley:  I will push the improved coverage and address your replies by this Friday (I have some Exams in the meantime)!

2022-02-24 07:35 UTC, JoshuaKGoldberg commented
Good luck on the exams! ❤️

2022-02-28 08:01 UTC, hyperupcall commented
I've implemented the changes, including use of `Set()`, `Object.entries()`, and got back to 100% codecov :smile: 

Also, both `explicit-function-return-type` and `explicit-module-boundary-types` are now used in the conversion process. Since I'm not super familiar with TSLint, I manually tested each one to be 100% sure conversion was the same. When this conversion is done, I added a message to to `notices` since ESLint seems to only lint all functions (not classifying between arrow functions and non-arrow functions as TSLint does with `arrow-call-signature` and `call-signature`. I tried my best to make it succinct, lemmie know if you have any improvements 


Thank you for your patience, and let me know if I missed anything or should make any other changes! ^w^

2022-02-28 16:59 UTC, JoshuaKGoldberg approved these changes
Super, thanks so much @hyperupcall! 🙌

2022-02-28 16:59 UTC, merged

2022-03-01 22:34 UTC, JoshuaKGoldberg commented
This should be available in tslint-to-eslint-config@2.12.0.