fix(prefer-arrow-functions): Allow `allowStandaloneDeclarations` by d…
typescript-eslint/tslint-to-eslint-config pull request #1719
Opened 2023-08-03 09:27 UTC by hyperupcall

…efault

## PR Checklist

-   [x] Addresses an existing issue: fixes #838
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

Change the default of `prefer-arrow/prefer-arrow-functions` so `allowStandaloneDeclarations` is enabled.

2023-08-03 14:46 UTC, JoshuaKGoldberg requested changes
Sorry for marking the issue as accepted without resolving the discussion - looks like the option is opt-in? But thanks for getting started!

2023-08-03 14:46 UTC, JoshuaKGoldberg commented on src/converters/lintConfigs/rules/ruleConverters/only-arrow-functions.ts
> +                        allowStandaloneDeclarations: true,
I poked through the issue (what a throwback!) and https://github.com/TristonJ/eslint-plugin-prefer-arrow/issues/16 as you'd linked - thanks for the info. It look to me like `allowStandaloneDeclarations` should only be output if `"allow-declarations"` is in the original rule. And we can get rid of the _`"ESLint does not support allowing standalone function declarations."`_ notice.

2023-10-01 09:24 UTC, hyperupcall commented
You're right - the property _is_ opt-in - that's my mistake. The new logic fixes the conversion result

2023-10-09 21:34 UTC, JoshuaKGoldberg approved these changes
🆒 thanks!

2023-10-09 21:34 UTC, merged